language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-19mode
  - jruby-18mode

before_install:
  - gem install bundler --version '~> 1.3'

gemfile:
  - Gemfile
  - gemfiles/3.0.gemfile

matrix:
  allow_failures:
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: 1.8.7
      gemfile: Gemfile
